package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/goccy/go-yaml"

	"backend/internal/config"
	"backend/internal/entity"
)

// export-rbac ดึง namespace + สมาชิกทุกคน (รวมเจ้าของ) + โควตาจาก DB มา generate เป็น
// Kubernetes RBAC manifest (Role + RoleBinding) จริงๆ ที่ apply เข้า cluster ได้ทันที
//
// ทำไมต้องมีเครื่องมือนี้: เดิม RBAC เป็น YAML ตายตัวที่ต้องแก้มือทุกครั้ง
// พอมีคนสร้าง/ออกจาก space DB เราเปลี่ยน แต่ YAML เดิมไม่เปลี่ยนตาม ต้องมีคนจำแก้เอง
// เครื่องมือนี้เลยทำให้ DB เป็น source of truth เดียว — รันคำสั่งนี้เมื่อไรก็ได้ YAML ที่ตรงกับ
// DB ปัจจุบันเป๊ะ ไม่ต้องแก้มือ (จะรันมือเป็นครั้งคราว หรือจะเอาไปต่อ cron/CI ทีหลังก็ได้)
//
// data flow: config.Load → ConnectDBReadOnly (ต่อ DB เฉยๆ ไม่ AutoMigrate/แตะ FK — เครื่องมือนี้
// อ่านอย่างเดียว ไม่ควรมี DDL แอบยิงทุกครั้งที่รัน ต่างจาก cmd/server กับ cmd/seed)
// → SELECT namespaces ทั้งหมด → SELECT users ที่มี namespace_id ทีเดียว (กัน N+1 query) แล้ว
// group เป็น map[namespaceID][]User → ประกอบ Role+RoleBinding ต่อ namespace โดย bind สมาชิก
// ทุกคนเข้า Role เดียวกัน (ไม่ใช่แค่เจ้าของ) → เขียนรวมเป็นไฟล์เดียว (multi-document YAML คั่นด้วย "---")
//
// รัน: go run ./cmd/export-rbac [--out=rbac.yaml]
func main() {
	outPath := flag.String("out", "rbac.yaml", "path ของไฟล์ YAML ที่จะเขียนออก")
	flag.Parse()

	cfg := config.Load()
	db := config.ConnectDBReadOnly(cfg.DBUrl)

	var namespaces []entity.Namespace
	if err := db.Order("id").Find(&namespaces).Error; err != nil {
		log.Fatalf("อ่าน namespaces ไม่สำเร็จ: %v", err)
	}

	// ดึงสมาชิกของทุก namespace มาทีเดียว (ไม่ query ทีละ namespace) แล้ว group เอาเอง
	// .Order("id") ทำให้ลำดับ subject ใน RoleBinding นิ่งเสมอ — รันกี่ครั้งก็ได้ไฟล์เหมือนเดิม
	var members []entity.User
	if err := db.Where("namespace_id IS NOT NULL").Order("id").Find(&members).Error; err != nil {
		log.Fatalf("อ่านสมาชิกไม่สำเร็จ: %v", err)
	}
	membersByNamespace := make(map[int][]entity.User, len(namespaces))
	for _, u := range members {
		membersByNamespace[*u.NamespaceID] = append(membersByNamespace[*u.NamespaceID], u)
	}

	var buf bytes.Buffer
	buf.WriteString("# generated by `go run ./cmd/export-rbac` — DB คือ source of truth, ห้ามแก้ไฟล์นี้ตรงๆ\n")
	buf.WriteString(fmt.Sprintf("# สร้างจาก %d namespace ใน DB — รันคำสั่งเดิมซ้ำเมื่อไรก็ได้ผลลัพธ์ล่าสุดเสมอ\n", len(namespaces)))

	written := 0
	for _, ns := range namespaces {
		nsMembers := membersByNamespace[ns.ID]

		owner, ok := findOwner(nsMembers, ns.ContributorID)
		if !ok {
			// ไม่ควรเกิดขึ้นจริง (fk_namespaces_contributor_id + invariant "เจ้าของเป็นสมาชิกของ
			// namespace ตัวเองเสมอ" บังคับไว้อยู่แล้ว ดู namespace_manager.go) กันไว้เผื่อ DB
			// อยู่ระหว่าง migrate/ไม่ sync — ข้ามแล้วเตือน ดีกว่าทำให้ generate ทั้งไฟล์พังไปด้วย
			log.Printf("!! ข้าม namespace '%s' (id=%d): หา contributor (user id=%d) ในกลุ่มสมาชิกไม่เจอ",
				ns.Name, ns.ID, ns.ContributorID)
			continue
		}

		for _, doc := range namespaceManifests(ns, owner, nsMembers) {
			b, err := yaml.Marshal(doc)
			if err != nil {
				log.Fatalf("marshal manifest ของ namespace '%s' ไม่สำเร็จ: %v", ns.Name, err)
			}
			buf.WriteString("---\n")
			buf.Write(b)
		}
		written++
	}

	// ไม่เขียนทับไฟล์เดิมด้วย manifest ว่าง — manifest ที่ไม่มี document เลย (0 namespace หรือ
	// ทุก namespace ถูกข้าม) ทำให้ `kubectl apply -f` ล้มทันทีด้วย "no objects passed to apply"
	// ทั้งที่ export-rbac เองไม่เจอ error ระหว่างเขียนไฟล์เลยแล้วจะรายงานว่าสำเร็จ (exit 0) —
	// ให้ fail ดังๆ ตั้งแต่ขั้น generate แทน จะได้ไม่ต้องไปเจอ error ที่โยงกลับมาไม่ถึงตอน apply
	// จริง และไฟล์ล่าสุดที่ยัง apply ได้ (ถ้ามี) จะไม่ถูกเขียนทับด้วยของที่ใช้ไม่ได้
	if written == 0 {
		log.Fatalf("!! ไม่มี namespace ไหน generate manifest ได้เลย (พบ %d namespace ใน DB) — "+
			"ไม่เขียนไฟล์ '%s' ทับของเดิม เพราะ manifest ว่างจะทำให้ `kubectl apply` พังทันที",
			len(namespaces), *outPath)
	}

	if err := os.WriteFile(*outPath, buf.Bytes(), 0o644); err != nil {
		log.Fatalf("เขียนไฟล์ '%s' ไม่สำเร็จ: %v", *outPath, err)
	}
	log.Printf("เขียน RBAC manifest ของ %d/%d namespace ลง '%s' สำเร็จ ✓", written, len(namespaces), *outPath)
}

// findOwner หา contributor ในลิสต์สมาชิกของ namespace เดียวกัน (ทั้งคู่มาจาก DB คนละ query
// เลยต้องจับคู่เอาเองแทนที่จะเชื่อว่า DB คืนมาตรงกันเสมอ)
func findOwner(members []entity.User, contributorID int) (entity.User, bool) {
	for _, u := range members {
		if u.ID == contributorID {
			return u, true
		}
	}
	return entity.User{}, false
}

// namespaceManifests ประกอบ Role + RoleBinding ของ namespace เดียว
//
// ขอบเขตสิทธิ์ (Role rules) จงใจให้ตรงกับสิ่งที่ backend อนุญาตให้ทำผ่าน API อยู่แล้วเท่านั้น
// ไม่ให้เกินไปกว่านั้น:
//   - deployments/services: full CRUD — ตรงกับที่ ServiceManager.Create/Delete ทำผ่าน DeployService/
//     DeleteService (ดู services/provisioner.go)
//   - pods: get/list/watch + pods/log get — สำหรับหน้า monitoring เท่านั้น
//   - "ห้าม" pods/exec โดยตั้งใจ — ตรงกับ entity.UserContainer ที่กำกับไว้ชัดว่า
//     "ใช้ terminal ไม่ได้ ได้แค่ monitoring" ถ้าจะเปิด exec ทีหลังต้องเพิ่ม resource นี้เอง
//     ไม่ใช่ default ที่เครื่องมือนี้จะออกให้
//
// Subjects ของ RoleBinding ผูก "สมาชิกทุกคนในกลุ่ม" เข้า Role เดียวกันหมด ไม่ใช่แค่เจ้าของ
// เพราะ ServiceController ฝั่ง backend ให้สมาชิกทุกคนใน namespace สร้าง/ลบ/เห็น service ร่วมกัน
// เท่ากันอยู่แล้ว ("สมาชิกทุกคนในกลุ่มเห็น service ของกลุ่มเหมือนกันหมด" — ดู service_controller.go)
// ถ้า RBAC บน cluster bind แค่เจ้าของ จะเกิดช่องว่างที่ backend อนุญาตแต่ k8s บล็อกสมาชิกที่เหลือ
//
// โควตา (cpu_limit_milli/ram_limit_mb) ไม่ใช่ concept ของ RBAC ตรงๆ (ของจริงคือ k8s ResourceQuota
// คนละ kind) แต่ใส่เป็น annotation ไว้บน RoleBinding ให้เห็นในไฟล์เดียวกันว่ากลุ่มนี้ได้โควตาเท่าไหร่
// และใครเป็นเจ้าของ (contributor) — สะดวกตอนอ่าน diff/review ไม่ต้องเปิด DB ควบคู่
func namespaceManifests(ns entity.Namespace, owner entity.User, members []entity.User) []any {
	role := rbacRole{
		APIVersion: "rbac.authorization.k8s.io/v1",
		Kind:       "Role",
		Metadata: objectMeta{
			Name:      "owner",
			Namespace: ns.Name,
		},
		Rules: []policyRule{
			{APIGroups: []string{"apps"}, Resources: []string{"deployments"}, Verbs: []string{"get", "list", "watch", "create", "update", "patch", "delete"}},
			{APIGroups: []string{""}, Resources: []string{"services"}, Verbs: []string{"get", "list", "watch", "create", "update", "patch", "delete"}},
			{APIGroups: []string{""}, Resources: []string{"pods"}, Verbs: []string{"get", "list", "watch"}},
			{APIGroups: []string{""}, Resources: []string{"pods/log"}, Verbs: []string{"get"}},
		},
	}

	subjects := make([]subject, 0, len(members))
	for _, u := range members {
		subjects = append(subjects, subject{
			Kind:     "User",
			APIGroup: "rbac.authorization.k8s.io",
			// ดู README: ยังไม่มีระบบที่ map identity จริงเข้ากับ subject นี้ (auth ของ Caesar Cluster
			// เป็น JWT ระดับ backend API เท่านั้น ไม่ได้คุยกับ k8s โดยตรง) — ตอนนี้เป็นแค่ชื่อ subject
			// ที่เดาไว้ก่อน ต้องออกแบบ auth layer ที่แปลง identity จริง → subject นี้ก่อนเอาไปใช้งานจริง
			Name: "caesar-user-" + u.StudentID,
		})
	}

	binding := rbacRoleBinding{
		APIVersion: "rbac.authorization.k8s.io/v1",
		Kind:       "RoleBinding",
		Metadata: objectMeta{
			Name:      "owner-binding",
			Namespace: ns.Name,
			Annotations: map[string]string{
				"caesar-cluster.io/contributor-student-id": owner.StudentID,
				"caesar-cluster.io/member-count":           fmt.Sprint(len(members)),
				"caesar-cluster.io/cpu-limit-milli":        fmt.Sprint(ns.CPULimitMilli),
				"caesar-cluster.io/ram-limit-mb":           fmt.Sprint(ns.RAMLimitMB),
			},
		},
		Subjects: subjects,
		RoleRef: roleRef{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "Role",
			Name:     role.Metadata.Name,
		},
	}

	return []any{role, binding}
}

// ด้านล่างเป็น struct ขั้นต่ำที่ตรงกับ schema จริงของ k8s rbac.authorization.k8s.io/v1
// (Role/RoleBinding) เขียนเองแทนการดึง k8s.io/api มาทั้งก้อน เพราะต้องการแค่ marshal เป็น YAML
// ไม่ได้เรียก k8s API ตรงๆ จากเครื่องมือนี้ — เอาไฟล์ที่ได้ไป kubectl apply -f เองอีกที
type objectMeta struct {
	Name        string            `yaml:"name"`
	Namespace   string            `yaml:"namespace"`
	Annotations map[string]string `yaml:"annotations,omitempty"`
}

type policyRule struct {
	APIGroups []string `yaml:"apiGroups"`
	Resources []string `yaml:"resources"`
	Verbs     []string `yaml:"verbs"`
}

type rbacRole struct {
	APIVersion string       `yaml:"apiVersion"`
	Kind       string       `yaml:"kind"`
	Metadata   objectMeta   `yaml:"metadata"`
	Rules      []policyRule `yaml:"rules"`
}

type subject struct {
	Kind     string `yaml:"kind"`
	APIGroup string `yaml:"apiGroup,omitempty"`
	Name     string `yaml:"name"`
}

type roleRef struct {
	APIGroup string `yaml:"apiGroup"`
	Kind     string `yaml:"kind"`
	Name     string `yaml:"name"`
}

type rbacRoleBinding struct {
	APIVersion string     `yaml:"apiVersion"`
	Kind       string     `yaml:"kind"`
	Metadata   objectMeta `yaml:"metadata"`
	Subjects   []subject  `yaml:"subjects"`
	RoleRef    roleRef    `yaml:"roleRef"`
}
